name = "Jamalam's Modpack"
author = "Jamalam"
version = "24.07.2023-build.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0978ebdb2962754f5ac424561daed8a054beb0e510ef3fe0a4e55e6ba18d7c9"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
