name = "Jamalam's Modpack"
author = "Jamalam"
version = "01.08.2023-build.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cf70964062cd661d5b259b85f36d8e1901d0c7631d458eca1ef139f211a3234"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
