name = "Jamalam's Modpack"
author = "Jamalam <james[at]jamalam.tech | jamalam#0001>"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e285abef8cc909c95abd6f93d15a4d8b94ed162964232866141e348eca113ca"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.26"

[options]
acceptable-game-versions = ["1.19.2"]
