name = "Jamalam's Modpack"
author = "Jamalam <james[at]jamalam.tech | jamalam#0001>"
version = "2.0.0+alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3794cc7b20a83d8da633a11e84af5ff1c7fc89666196017842aca194b9f82f51"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.21"

[options]
acceptable-game-versions = ["1.19.2"]
