name = "Jamalam's Modpack"
author = "Jamalam"
version = "15.07.2023-build.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cf4bc775df8683ca9f29c8546e4cba4c08459d7bca3b28ea68cce0f57be6eac"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
