name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58635048685e1232db64d3279f016839e46da3fe8c2a94f53931b3fa925a1296"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.6"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
