name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5728fd69137760db48ca23215287acd8c6e6b41cc514a70b72429feba7ffff4"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
