name = "Jamalam's Modpack"
author = "Jamalam"
version = "01.08.2023-build.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1574584463130fafe8341b937e358c1129606e1fa36ace607a83e2f2ca1640f"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
