name = "Jamalam's Modpack"
author = "Jamalam <james[at]jamalam.tech | jamalam#0001>"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7276cb78928dc9635646d9be2198633b7eccf124ee2f5512af7517e76fef8b9"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.23"

[options]
acceptable-game-versions = ["1.19.2"]
