name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89045125f2fd37f2e28944439d9755b60f5927c702370c427f42e97b8f13f272"

[versions]
minecraft = "1.18.2"
quilt = "0.17.2-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
