name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68d6fc3f079a33a2b84a5763c18d84953d04e49551f0bd8492d0efb05079ba9e"

[versions]
minecraft = "1.18.2"
quilt = "0.17.2-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
