name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd00ed3d660068f9cc9b70f959dbcfea08eaafed0e65e98d097df1e9caf0f74e"

[versions]
minecraft = "1.18.2"
quilt = "0.17.2-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
