name = "Jamalam's Modpack"
author = "Jamalam"
version = "25.07.2023-build.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43320ed0bb489ceda0e436b36240f6e62c241d7fd1ce8708719c5ce3c200e9bc"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
