name = "Jamalam's Modpack"
author = "Jamalam <james[at]jamalam.tech | jamalam#0001>"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5cfc79dd5161e46f8e43384b7ca4c9b8b3b553c2777cff70e512d4ae951c232"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"

[options]
acceptable-game-versions = ["1.19.2"]
