name = "Jamalam's Modpack"
author = "Jamalam <james[at]jamalam.tech | jamalam#0001>"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afd62f6d37ef5897166f583cd4da861fb5e2d57a12471ebf16a2f6aeffd2bc43"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"

[options]
acceptable-game-versions = ["1.19.2"]
