name = "Jamalam's Modpack"
author = "Jamalam <james[at]jamalam.tech | jamalam#0001>"
version = "2.0.0+beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e15a3ab38cb2b20ac301c57f9ffb0f7a332c72547538f63be5d3cded8841c99"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.23"

[options]
acceptable-game-versions = ["1.19.2"]
