name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56c216a8cbe3b2242158a5c25b7b823b19ac0a33f1182b0792c1275958cc31de"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.6"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
