name = "Jamalam's Modpack"
author = "Jamalam"
version = "22.08.2023-build.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63c200f754b5ae9866582b71d18bf65969b4c56f3a5c486bb7178a6dd5a7125e"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
