name = "Jamalam's Modpack"
author = "Jamalam"
version = "22.07.2023-build.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b287845dd5ac7bcbe06fff9f0888d7761c0bc0b4ac3551c4bb80548c77119c7"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
