name = "Jamalam's Modpack"
author = "Jamalam"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c563289dce81f30193d516b1e8ea2585fb8ec23a748ccce7c46d5d31ee419ccd"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
