name = "Jamalam's Modpack"
author = "Jamalam"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9b8b23d877bf46d9029d68216c462af52950d466f80e1f5c6a45c4c2fcef421"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
