name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94b5f231354a68a0765b90409cd415f4a02a5fbfb9610b0c73ba26d58b397c0e"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.6"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
