name = "Jamalam's Modpack"
author = "Jamalam"
version = "01.08.2023-build.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59d5c8ec9124aac698964fa2ce9dfe47d761fde8a93acb807f3e5b4ec273a78f"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
