name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4407176fe24f9c895795b5cfc3779cea863315afee56027f6485e1f250ce95fb"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
