name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a919fe8728b7ff7950b08ff839940835bdaf15ab1ac4a2a38af107afb033eff"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
