name = "Jamalam's Modpack"
author = "Jamalam"
version = "24.07.2023-build.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20f6685b23a148cb569027621c930180171689e3bfb1f705cd32d7c13a19b6b7"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
