name = "Jamalam's Modpack"
author = "Jamalam"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6a9c3220b125ce81cb8adab1ab1bde9d1d8f6cb77b89bb94eba1c89af3a805a"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1-beta.3"
