name = "Jamalam's Modpack"
author = "Jamalam"
version = "25.07.2023-build.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baf72948ce45dc8517312e97caa325fefe544f93b7ee816f478188b5f158c7b9"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
