name = "Jamalam's Modpack"
author = "Jamalam"
version = "24.07.2023-build.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "885e7d0719be8dbd4a1643e6eb9b7402f16c7f6fcfd34bf04aff112a8ec89bbf"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
