name = "Jamalam's Modpack"
author = "Jamalam"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b90337da6761da48dd33c505e98754d644690acffb7e150fba6ae9e111d2c7c"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1-beta.3"
