name = "Jamalam's Modpack"
author = "Jamalam"
version = "24.07.2023-build.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6f218c8fa6a978582283b07cbffcb5185f67b48161b91e2845c95a609748fb7"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
