name = "Jamalam's Modpack"
author = "Jamalam"
version = "28.07.2023-build.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e492988c732b6a647dcd770d7102119562c681490536a4e9d54da0bfb0993c5"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
