name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb612cb137067f788a35c25219fac0594e75c45ce73d196e176ecf286da9afd5"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
