name = "Jamalam's Modpack"
author = "Jamalam"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0b400731495ff50dcadff6d17d08d124c85ec96afa067369e8694a2a6b66cc6"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
