name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d594bfa2a6fd27a5c9c3690a785950ce6b6df0078fa5386b2222d9eee3cc8642"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
