name = "Jamalam's Modpack"
author = "Jamalam"
version = "09.08.2023-build.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeabaf31c92a0d905480b4ce24bd2faafba8f1a85d754d046f35afcfae49967f"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
