name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c10ea16842d0db05cdfc8c0d66d0fcd705a875d57931be8e767b8333fc4600ab"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.6"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
