name = "Jamalam's Modpack"
author = "Jamalam"
version = "24.07.2023-build.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7a0ca573118c8e77e09d18aaaf9624c8d79cb9b5037d0a9b1fec884b8f70c93"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
