name = "Jamalam's Modpack"
author = "Jamalam <james[at]jamalam.tech | jamalam#0001>"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8c3638ed0189d0edd0eff633ea0f071c82c16e61e7e99b5a114da75e9a7f756"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.27"

[options]
acceptable-game-versions = ["1.19.2"]
