name = "Jamalam's Modpack"
author = "Jamalam"
version = "14.07.2023-build.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8c378a9fa1aafb624b56101ca83332e312a6486465312625af8df01f36db915"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
