name = "Jamalam's Modpack"
author = "Jamalam <james<at>jamalam.tech | jamalam#0001>"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00fdd121ca4aefc4287f1caec8b869d2a0230002a339fc38b294942eb96f98a7"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19.2"]
