name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfc21ab883b69c0c3aaa6341f451a48026fd9fb168f58f6377303422a0e19bfb"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
