name = "Jamalam's Modpack"
author = "Jamalam"
version = "27.07.2023-build.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a7def3e66150cadc94b39f38882bd0216edff7b196a2d417f7953ed4f67d3a3"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
