name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29f02beb3bafbc21aed7e1c9cb73ef3edee912731c24a5485243da19ecec221b"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
