name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06406cb9a14c1616ee1b3e156c432bd4a43e00fbec613e8f39b3a82c02f82116"

[versions]
minecraft = "1.18.2"
quilt = "0.17.2-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
