name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "806634de0f39001b9b7e4e05a127a9aa1437cbe0106c33fc00a9c68101360633"

[versions]
minecraft = "1.18.2"
quilt = "0.17.2-beta.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
