name = "Jamalam's Modpack"
author = "Jamalam"
version = "01.08.2023-build.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adfe535d3eabd3f50019aed24ff0e84ca459bb6512f67de7edb39213fef289b9"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
