name = "Jamalam's Modpack"
author = "Jamalam"
version = "24.07.2023-build.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f11b94ce43cbc49a80a46672c4355535ee72e3d22deea88651bb9b4cac6f8c60"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
