name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e49b29c897416fefc32695eab8bb081794129718114963983fb2908732201fc"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.6"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
