name = "Jamalam's Modpack"
author = "Jamalam <james[at]jamalam.tech | jamalam#0001>"
version = "2.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8f628d4c5c2bad9f313b1ffc6ea3ab07d57a1b42f279408fe7c0f1b67f6c1b9"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.25"

[options]
acceptable-game-versions = ["1.19.2"]
