name = "Jamalam's Modpack"
author = "Jamalam"
version = "01.08.2023-build.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cc0b086c9e16f53c3558925a891d1fc18cdedd9f516670fc3c5c1a51593504a"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
