name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc8e20b08f2e2db8713718a2f519989654b402d3c6fd3856e85fab18498a2a86"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
