name = "Jamalam's Modpack"
author = "Jamalam"
version = "07.08.2023-build.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5d3b890de6d49f7b0af77e9f1557bdcffbaa98cda743f6ee743a929f84494ac"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
