name = "Jamalam's Modpack"
author = "Jamalam"
version = "1.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e28f2db46d0079e7c6f4c44b4681a0ce8729894cdebaef354c10c3ab16a0f02"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.6"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2"]
