name = "Jamalam's Modpack"
author = "Jamalam"
version = "25.07.2023-build.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc2d3422ac7a654d33218de5f536b7c97f5692e87b086cbef24bb2dd5141b882"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
