name = "Jamalam's Modpack"
author = "Jamalam"
version = "01.08.2023-build.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69af8b16409d4fd10c146a28a017b50ab367d1598b5697de277835961d0ae985"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
