name = "Debugify"
filename = "debugify-1.10.0-fabric-1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/QwxR6Gcd/versions/1.10.0-fabric/debugify-1.10.0-fabric-1.18.2.jar"
hash-format = "sha1"
hash = "fe088b453202cb3f3872790202f1d10e18e5309f"

[update]
[update.modrinth]
mod-id = "QwxR6Gcd"
version = "XtJaW95T"
