name = "Immersive Portals"
filename = "immersive-portals-1.3.9-mc1.18.2-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/zJpHMkdD/versions/1.3.9-1.18.2/immersive-portals-1.3.9-mc1.18.2-fabric.jar"
hash-format = "sha1"
hash = "ee033e48ace61b0e0b08b7b1383d0d3fa00eae78"

[update]
[update.modrinth]
mod-id = "zJpHMkdD"
version = "jv8F9Bes"
