name = "MCDiscordChat"
filename = "MCDiscordChat-1.18-2.0.0-alpha.2.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/D0sHdnXY/versions/2.0.0-alpha.2_1.18/MCDiscordChat-1.18-2.0.0-alpha.2.jar"
hash-format = "sha1"
hash = "f67f420e9e17173e68b900a9980ae5e6dc6601b7"

[update]
[update.modrinth]
mod-id = "D0sHdnXY"
version = "nA7VNMLm"
