name: Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Python 3
      uses: actions/setup-python@v2
    - name: Install Sculk
      run: python3 <(wget https://raw.githubusercontent.com/sculk-cli/sculk/main/install.py -q -O-)
    - name: Check hashes
      run: ~/.sculk/sculk refresh --check
