name: Deploy Modpack

on: push

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Send API Request
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.API_DEPLOY_KEY }}" https://server-api.jamalam.tech/deploy/pack
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Upload Files to Minecraft Server
        run: |
          deno run --allow-read --allow-net --allow-write --allow-run --no-check ./upload_to_server.ts ${{ secrets.FTP_HOST }} ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
