name: Publish Modpack

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Publish to pack.jamalam.tech
        run: |
          curl --silent --show-error --fail -X POST -H "Authorization: Bearer ${{ secrets.API_DEPLOY_KEY }}" https://orion.jamalam.tech/deploy/pack
