name: Publish Modpack

on:
  push:
    tags:
      - '*'

jobs:
  deploy-main:
    runs-on: ubuntu-22.04

    steps:
      - name: Publish to pack.jamalam.tech
        run: |
          curl --silent --show-error --fail -X POST -H "Authorization: Bearer ${{ secrets.API_DEPLOY_KEY }}" https://orion.jamalam.tech/deploy/pack

      - name: Install Go
        uses: actions/setup-go@v2

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Get Version Number
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Package Modpack
        run: packwiz modrinth export -o jamalams-pack-$VERSION.mrpack
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jamalams-pack-$VERSION.mrpack
          path: jamalams-pack-$VERSION.mrpack

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: TODO
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            jamalams-pack-$VERSION.mrpack

          name: Jamalam's Pack ($VERSION)
          version: $VERSION
          version-type: release

          loaders: |
            quilt
          game-versions: |
            1.20.1
