name: Deploy Modpack

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Send API Request
        run: |
          curl --silent --show-error --fail -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.API_DEPLOY_KEY }}" https://orion.jamalam.tech/deploy/pack
