name: Update Datapack

on:
  push:
    paths:
      - 'datapack/**'
      - '.github/workflows/package-datapack.yml'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  package-datapack:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Update Datapack Zip
        run: |
          rm -f global_packs/required_data/jamalams-modpack.zip
          cd datapack
          zip -r ../global_packs/required_data/jamalams-modpack.zip .

      - uses: EndBug/add-and-commit@v9
        with:
          message: '[Bot] Update datapack' 
          add: global_packs/required_data/jamalams-modpack.zip
