name: Update Datapack

on:
  push:
    branches:
      - next
    paths:
      - 'datapack'

jobs:
  update-datapack:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Update Datapack Zip
        run: ./tools/package_datapack
        shell: bash

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[Bot] Update datapack' 
          file_pattern: global_data_pack/JQM.zip
